# Generated by Django 5.2.15 on 2026-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("oauth_provider__gt", "")),
                fields=("oauth_provider", "oauth_subject"),
                name="unique_oauth_identity",
            ),
        ),
    ]
