# Generated by Django 5.2.15 on 2026-06-14 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="restaurants.region",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="JjambbongRestaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("detail_address", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("opening_hours", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "soup_style",
                    models.CharField(
                        choices=[
                            ("MEAT", "고기 육수"),
                            ("SEAFOOD", "해물 육수"),
                            ("MIXED", "혼합 육수"),
                            ("UNKNOWN", "미분류"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "spice_level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("average_price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sentiment_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("youtube_featured", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restaurants",
                        to="restaurants.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="restaurants/"),
                ),
                ("image_url", models.URLField(blank=True)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_signature", models.BooleanField(default=False)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_restaurants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["name"], name="restaurants_name_d2e6cd_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["is_active"], name="restaurants_is_acti_b51cf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jjambbongrestaurant",
            index=models.Index(fields=["name"], name="restaurants_name_b62030_idx"),
        ),
        migrations.AddIndex(
            model_name="jjambbongrestaurant",
            index=models.Index(
                fields=["region", "is_visible"], name="restaurants_region__15a44c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jjambbongrestaurant",
            index=models.Index(
                fields=["soup_style"], name="restaurants_soup_st_fc0282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jjambbongrestaurant",
            index=models.Index(
                fields=["spice_level"], name="restaurants_spice_l_cbaadf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jjambbongrestaurant",
            index=models.Index(
                fields=["sentiment_score"], name="restaurants_sentime_09b384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantimage",
            index=models.Index(
                fields=["restaurant", "is_primary"],
                name="restaurants_restaur_04b7e6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurantmenu",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_menu_name_per_restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "restaurant"), name="unique_user_favorite_restaurant"
            ),
        ),
    ]
