# Generated by Django 5.2.15 on 2026-06-17 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=120)),
                ("normalized_keyword", models.CharField(max_length=120, unique=True)),
                ("search_count", models.PositiveIntegerField(default=0)),
                (
                    "first_searched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_searched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-search_count", "-last_searched_at", "keyword"],
                "indexes": [
                    models.Index(
                        fields=["-search_count", "-last_searched_at"],
                        name="analytics_s_search__cc1bca_idx",
                    ),
                    models.Index(
                        fields=["last_searched_at"],
                        name="analytics_s_last_se_6a90fe_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=120)),
                ("normalized_keyword", models.CharField(max_length=120)),
                ("result_count", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["normalized_keyword", "created_at"],
                        name="analytics_s_normali_da621f_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_s_user_id_2cb926_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_s_created_269249_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page view"),
                            ("detail_view", "Detail view"),
                        ],
                        default="page_view",
                        max_length=30,
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("full_url", models.TextField(blank=True)),
                ("referrer", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_key", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_logs",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_v_event_t_cacc60_idx",
                    ),
                    models.Index(
                        fields=["path", "created_at"],
                        name="analytics_v_path_58be9b_idx",
                    ),
                    models.Index(
                        fields=["restaurant", "created_at"],
                        name="analytics_v_restaur_16fc16_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_v_user_id_d76fa4_idx",
                    ),
                ],
            },
        ),
    ]
