# Generated by Django 5.2.15 on 2026-06-14 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("NAVER_BLOG", "네이버 블로그"),
                            ("YOUTUBE", "유튜브"),
                            ("USER", "사용자 제보"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=120)),
                ("content", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_advertorial", models.BooleanField(default=False)),
                ("quality_score", models.PositiveSmallIntegerField(default=0)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_sources",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "source_type"],
                        name="reviews_rev_restaur_8d5c42_idx",
                    ),
                    models.Index(
                        fields=["is_advertorial"], name="reviews_rev_is_adve_321c36_idx"
                    ),
                ],
            },
        ),
    ]
