# Generated by Django 5.2.15 on 2026-07-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="linked_restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_reports",
                to="restaurants.jjambbongrestaurant",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="restaurant_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="restaurant_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
