# Generated by Django 5.2.15 on 2026-07-09 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_question_linked_restaurant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUG", "버그 신고"),
                            ("SUGGESTION", "제안"),
                            ("PRAISE", "칭찬"),
                            ("OTHER", "기타"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("page_path", models.CharField(blank=True, max_length=512)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "created_at"],
                        name="community_f_is_reso_1c9be4_idx",
                    ),
                    models.Index(
                        fields=["category"], name="community_f_categor_9f213e_idx"
                    ),
                ],
            },
        ),
    ]
