# Generated by Django 5.2.15 on 2026-06-14 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "blog_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "youtube_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("ai_summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("is_latest", models.BooleanField(default=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=80)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=1, max_digits=6),
                ),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keywords",
                        to="ai_analysis.aianalysisresult",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-weight", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="SentimentAspectScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("soup", "국물 맛"),
                            ("spiciness", "매운맛"),
                            ("fire", "불향"),
                            ("noodle", "면 식감"),
                            ("topping", "해산물/고명"),
                            ("quantity", "양"),
                            ("price", "가격 만족도"),
                            ("waiting", "웨이팅"),
                            ("hygiene", "위생"),
                            ("service", "서비스"),
                            ("return_intent", "재방문 의사"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect_scores",
                        to="ai_analysis.aianalysisresult",
                    ),
                ),
            ],
            options={
                "ordering": ["aspect"],
            },
        ),
        migrations.CreateModel(
            name="WordCloudResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="wordclouds/"),
                ),
                ("image_url", models.URLField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wordcloud_results",
                        to="ai_analysis.aianalysisresult",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordcloud_results",
                        to="restaurants.jjambbongrestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["restaurant", "is_latest"],
                name="ai_analysis_restaur_e270b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(fields=["status"], name="ai_analysis_status_42cc52_idx"),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["total_score"], name="ai_analysis_total_s_26c1d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurantkeyword",
            index=models.Index(
                fields=["restaurant", "keyword"], name="ai_analysis_restaur_10cd88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sentimentaspectscore",
            constraint=models.UniqueConstraint(
                fields=("analysis", "aspect"), name="unique_aspect_per_analysis"
            ),
        ),
        migrations.AddIndex(
            model_name="wordcloudresult",
            index=models.Index(
                fields=["restaurant", "generated_at"],
                name="ai_analysis_restaur_c39336_idx",
            ),
        ),
    ]
